import { useEffect, useRef, useState } from 'react' ; import { api } from '../api/client' ;
declare global { interface Window { mapgl?: any } }
let mapglPromise: Promise<any> | null = null ;
const loadMapgl = () => { if (!mapglPromise) { mapglPromise = new Promise((resolve, reject) => { if (window.mapgl) { resolve(window.mapgl) ; return ; } const script = document.createElement('script') ; script.src = 'https://mapgl.2gis.com/api/js/v1' ; script.async = true ; script.onload = () => { if (window.mapgl) { resolve(window.mapgl) } else { mapglPromise = null ; reject(new Error('API 2GIS загрузился некорректно')) } } ; script.onerror = () => { mapglPromise = null ; reject(new Error('Не удалось загрузить API 2GIS')) } ; document.head.appendChild(script) ; }) ; } return mapglPromise ; } ;
// Геокодирование адреса через Каталог 2GIS (items/geocode возвращает координаты в fields=items.point)
const geocodeDgis = async (address: string, apiKey: string): Promise<[number, number] | null> => { const url = `https://catalog.api.2gis.com/3.0/items/geocode?q=${encodeURIComponent(address)}&fields=items.point&key=${encodeURIComponent(apiKey)}` ; const res = await fetch(url) ; if (!res.ok) throw new Error(`geocode http ${res.status}`) ; const data = await res.json() ; if (data?.meta?.code && data.meta.code !== 200) throw new Error(data?.meta?.error?.message || `geocode code ${data.meta.code}`) ; const item = data?.result?.items?.[0] ; const point = item?.point ; if (!point) return null ; return [point.lon, point.lat] ; } ;
const retryButtonStyle: React.CSSProperties = { marginTop: 8, padding: '6px 14px', borderRadius: 8, border: '1px solid var(--border-color)', background: 'var(--bg-card)', color: 'var(--text-primary)', cursor: 'pointer', fontSize: 13 } ;
export function DgisMap({ address }: { address: string }) { const containerRef = useRef<HTMLDivElement>(null) ; const mapRef = useRef<any>(null) ; const markerRef = useRef<any>(null) ; const [status, setStatus] = useState<'loading' | 'ready' | 'nokey' | 'notfound' | 'loaderror' | 'geoerror'>('loading') ; const [attempt, setAttempt] = useState(0) ;
  useEffect(() => { let cancelled = false ;
    (async () => { try { setStatus('loading') ; const s = await api.dgis.getSettings() ; const key = s?.apiKey ; if (!key) { if (!cancelled) setStatus('nokey') ; return } const mapgl = await loadMapgl() ; if (cancelled) return ;
      const showAddress = async (): Promise<boolean> => { const coords = await geocodeDgis(address, key) ; if (!coords) return false ; if (!mapRef.current && containerRef.current) { mapRef.current = new mapgl.Map(containerRef.current, { center: coords, zoom: 16, key }) ; markerRef.current = new mapgl.Marker(mapRef.current, { coordinates: coords }) ; } else if (mapRef.current) { mapRef.current.setCenter(coords) ; if (markerRef.current) { markerRef.current.setCoordinates(coords) } else { markerRef.current = new mapgl.Marker(mapRef.current, { coordinates: coords }) } } return true } ;
      let ok = await showAddress() ; if (!ok && !cancelled) { await new Promise(r => setTimeout(r, 1500)) ; if (!cancelled) ok = await showAddress() } ; if (cancelled) return ; setStatus(ok ? 'ready' : 'notfound') ;
    } catch (e: any) { console.error('2GIS map error:', e) ; if (!cancelled) setStatus(String(e?.message || '').startsWith('geocode') ? 'geoerror' : 'loaderror') } })() ;
    return () => { cancelled = true } ;
  }, [address, attempt]) ;
  useEffect(() => () => { if (markerRef.current) { try { markerRef.current.destroy() } catch (e) { /* ignore */ } markerRef.current = null } ; if (mapRef.current) { try { mapRef.current.destroy() } catch (e) { /* ignore */ } mapRef.current = null } }, []) ;
  const retryBtn = <button type='button' onClick={() => setAttempt(a => a + 1)} style={retryButtonStyle}>Повторить</button> ;
  const box = (children: React.ReactNode) => <div style={{ padding: 16, borderRadius: 12, background: 'var(--bg-body)', fontSize: 13, color: 'var(--text-muted)' }}>{children}</div> ;
  if (status === 'nokey') return box(<>Для отображения карты укажите API-ключ 2GIS в Настройки → Интеграции → 2GIS{retryBtn}</>) ;
  if (status === 'geoerror') return box(<>Не удалось найти координаты через геокодер 2GIS. Проверьте, что у ключа в кабинете dev.2gis.ru подключён сервис «Каталоги».{retryBtn}</>) ;
  if (status === 'loaderror') return box(<>Не удалось загрузить карты 2GIS. Проверьте интернет-соединение и отключите блокировщик рекламы/трекеров для welans.cc.{retryBtn}</>) ;
  if (status === 'notfound') return box(<>Адрес «{address}» не найден на карте 2GIS. Проверьте правильность адреса.{retryBtn}</>) ;
  return <div ref={containerRef} style={{ width: '100%', height: 300, borderRadius: 12, overflow: 'hidden', border: '1px solid var(--border-color)', background: 'var(--bg-body)' }} /> ; }
