import { useEffect, useRef, useState } from 'react' ; import { api } from '../api/client' ;
declare global { interface Window { ymaps?: any } }
let ymapsPromise: Promise<any> | null = null ;
const loadYmaps = (apiKey: string) => { if (!ymapsPromise) { ymapsPromise = new Promise((resolve, reject) => { const script = document.createElement('script') ; script.src = `https://api-maps.yandex.ru/2.1/?apikey=${apiKey}&lang=ru_RU` ; script.async = true ; script.onload = () => resolve(window.ymaps) ; script.onerror = () => { ymapsPromise = null ; reject(new Error('Не удалось загрузить API Яндекс.Карт')) } ; document.head.appendChild(script) ; }) ; } return ymapsPromise ; } ;
export function YandexMap({ address }: { address: string }) { const containerRef = useRef<HTMLDivElement>(null) ; const mapRef = useRef<any>(null) ; const [status, setStatus] = useState<'loading' | 'ready' | 'nokey' | 'error'>('loading') ;
  useEffect(() => { let cancelled = false ; (async () => { try { const s = await api.yandex.getSettings() ; const key = s?.apiKey ; if (!key) { if (!cancelled) setStatus('nokey') ; return ; } const ymaps = await loadYmaps(key) ; if (cancelled) return ; await new Promise<void>((resolve) => ymaps.ready(() => resolve())) ; if (cancelled) return ; const res = await ymaps.geocode(address) ; if (cancelled) return ; const first = res.geoObjects.get(0) ; if (!first) { setStatus('error') ; return ; } const coords = first.geometry.getCoordinates() ; if (!mapRef.current && containerRef.current) { mapRef.current = new ymaps.Map(containerRef.current, { center: coords, zoom: 16, controls: ['zoomControl', 'geolocationControl'] }) ; } else if (mapRef.current) { mapRef.current.setCenter(coords, 16) ; mapRef.current.geoObjects.removeAll() ; } mapRef.current.geoObjects.add(new ymaps.Placemark(coords, { balloonContent: address })) ; setStatus('ready') ; } catch (e) { console.error('Yandex map error:', e) ; if (!cancelled) setStatus('error') ; } })() ; return () => { cancelled = true } ; }, [address]) ;
  useEffect(() => () => { if (mapRef.current) { mapRef.current.destroy() ; mapRef.current = null } }, []) ;
  if (status === 'nokey') return <div style={{ padding: 16, borderRadius: 12, background: 'var(--bg-body)', fontSize: 13, color: 'var(--text-muted)' }}>Для отображения карты укажите API-ключ Яндекс.Карт в Настройки → Интеграции → Яндекс</div> ;
  if (status === 'error') return <div style={{ padding: 16, borderRadius: 12, background: 'var(--bg-body)', fontSize: 13, color: 'var(--text-muted)' }}>Адрес не найден на карте. Проверьте правильность адреса.</div> ;
  return <div ref={containerRef} style={{ width: '100%', height: 300, borderRadius: 12, overflow: 'hidden', border: '1px solid var(--border-color)', background: 'var(--bg-body)' }} /> ; }
