import { useEffect, useRef, useState } from 'react' ; import { api } from '../api/client' ;
declare global { interface Window { ymaps?: any } }
let ymapsPromise: Promise<any> | null = null ;
const loadYmaps = (apiKey: string) => { if (!ymapsPromise) { ymapsPromise = new Promise((resolve, reject) => { if (window.ymaps) { resolve(window.ymaps) ; return ; } const script = document.createElement('script') ; script.src = `https://api-maps.yandex.ru/2.1/?apikey=${apiKey}&lang=ru_RU` ; script.async = true ; script.onload = () => { if (window.ymaps) { resolve(window.ymaps) } else { ymapsPromise = null ; reject(new Error('API Яндекс.Карт загрузился некорректно')) } } ; script.onerror = () => { ymapsPromise = null ; reject(new Error('Не удалось загрузить API Яндекс.Карт')) } ; document.head.appendChild(script) ; }) ; } return ymapsPromise ; } ;
const retryButtonStyle: React.CSSProperties = { marginTop: 8, padding: '6px 14px', borderRadius: 8, border: '1px solid var(--border-color)', background: 'var(--bg-card)', color: 'var(--text-primary)', cursor: 'pointer', fontSize: 13 } ;
export function YandexMap({ address }: { address: string }) { const containerRef = useRef<HTMLDivElement>(null) ; const mapRef = useRef<any>(null) ; const [status, setStatus] = useState<'loading' | 'ready' | 'nokey' | 'notfound' | 'loaderror' | 'apierror'>('loading') ; const [errorMsg, setErrorMsg] = useState('') ; const [attempt, setAttempt] = useState(0) ;
  useEffect(() => { let cancelled = false ; (async () => { try { setStatus('loading') ; setErrorMsg('') ; const s = await api.yandex.getSettings() ; const key = s?.apiKey ; if (!key) { if (!cancelled) setStatus('nokey') ; return ; } const ymaps = await loadYmaps(key) ; if (cancelled) return ; await new Promise<void>((resolve) => ymaps.ready(() => resolve())) ; if (cancelled) return ;
      const geocodeAndShow = async (): Promise<boolean> => { const res = await ymaps.geocode(address) ; const first = res.geoObjects.get(0) ; if (!first) return false ; const coords = first.geometry.getCoordinates() ; if (!mapRef.current && containerRef.current) { mapRef.current = new ymaps.Map(containerRef.current, { center: coords, zoom: 16, controls: ['zoomControl', 'geolocationControl'] }) ; } else if (mapRef.current) { mapRef.current.setCenter(coords, 16) ; mapRef.current.geoObjects.removeAll() ; } mapRef.current.geoObjects.add(new ymaps.Placemark(coords, { balloonContent: address })) ; return true ; } ;
      let ok = await geocodeAndShow() ; if (!ok && !cancelled) { await new Promise(r => setTimeout(r, 1500)) ; if (!cancelled) ok = await geocodeAndShow() ; } if (cancelled) return ; setStatus(ok ? 'ready' : 'notfound') ;
    } catch (e: any) { console.error('Yandex map error:', e) ; if (cancelled) return ; const msg = (e && e.message) ? String(e.message) : String(e) ; setErrorMsg(msg) ; setStatus(/загрузить|загрузился/i.test(msg) ? 'loaderror' : 'apierror') ; } })() ; return () => { cancelled = true } ; }, [address, attempt]) ;
  useEffect(() => () => { if (mapRef.current) { mapRef.current.destroy() ; mapRef.current = null } }, []) ;
  const retryBtn = <button type='button' onClick={() => setAttempt(a => a + 1)} style={retryButtonStyle}>Повторить</button> ;
  const box = (children: React.ReactNode) => <div style={{ padding: 16, borderRadius: 12, background: 'var(--bg-body)', fontSize: 13, color: 'var(--text-muted)' }}>{children}</div> ;
  if (status === 'nokey') return box(<>Для отображения карты укажите API-ключ Яндекс.Карт в Настройки → Интеграции → Яндекс{retryBtn}</>) ;
  if (status === 'loaderror') return box(<>Не удалось загрузить Яндекс.Карты. Проверьте интернет-соединение и отключите блокировщик рекламы/трекеров для этого сайта.{retryBtn}</>) ;
  if (status === 'notfound') return box(<>Адрес «{address}» не найден на карте. Проверьте правильность адреса.{retryBtn}</>) ;
  if (status === 'apierror') return box(<>Ошибка Яндекс.Карт: {errorMsg || 'неизвестная ошибка'}. Если ошибка повторяется только в мобильном браузере — проверьте ограничения API-ключа в кабинете разработчика Яндекс (должно быть ограничение по HTTP Referer «welans.cc», без ограничения по IP).{retryBtn}</>) ;
  return <div ref={containerRef} style={{ width: '100%', height: 300, borderRadius: 12, overflow: 'hidden', border: '1px solid var(--border-color)', background: 'var(--bg-body)' }} /> ; }
