import { User, Task, Contact, Deal, Project, Activity, DashboardStats, Role, Status, Comment, EmailSettings, ChatMessage, FileAttachment, TelephonySettings, Call, NovofonEmployee, TaskFinances, TaskTransaction, SmsMessage } from '../types'; const API_URL = ''; function getToken() { return localStorage.getItem('token'); } async function fetchApi(path: string, options?: RequestInit) { const res = await fetch(`${API_URL}${path}`, { ...options, headers: { 'Content-Type': 'application/json', ...(getToken() ? { Authorization: `Bearer ${getToken()}` } : {}), ...options?.headers, }, }); if (res.status === 401) { localStorage.removeItem('token'); window.location.reload(); throw new Error('Unauthorized'); } if (!res.ok) { const err = await res.json().catch(() => ({})); throw new Error(err.error || `HTTP ${res.status}`); } return res.json(); } export const api = { auth: { login: (login: string, password: string) => fetchApi('/api/auth/login', { method: 'POST', body: JSON.stringify({ login, password }) }), register: (email: string, password: string, name: string, username?: string) => fetchApi('/api/auth/register', { method: 'POST', body: JSON.stringify({ email, password, name, username }) }), me: (): Promise<User> => fetchApi('/api/auth/me'), }, tasks: { list: (params?: string): Promise<Task[]> => fetchApi(`/api/tasks${params ? `?${params}` : ''}`), get: (id: string): Promise<Task> => fetchApi(`/api/tasks/${id}`), history: (id: string) => fetchApi(`/api/tasks/${id}/history`), create: (data: Partial<Task>) => fetchApi('/api/tasks', { method: 'POST', body: JSON.stringify(data) }), update: (id: string, data: Partial<Task>) => fetchApi(`/api/tasks/${id}`, { method: 'PATCH', body: JSON.stringify(data) }), delete: (id: string) => fetchApi(`/api/tasks/${id}`, { method: 'DELETE' }), files: { list: (id: string): Promise<{name: string; size: number; createdAt: string}[]> => fetchApi(`/api/tasks/${id}/files`), upload: (id: string, formData: FormData) => fetch(`/api/tasks/${id}/files`, { method: 'POST', headers: { Authorization: `Bearer ${getToken()}` }, body: formData }).then(r => r.json()), delete: (id: string, filename: string) => fetchApi(`/api/tasks/${id}/files/${filename}`, { method: 'DELETE' }), download: (id: string, filename: string) => fetch(`${API_URL}/api/tasks/${id}/files/${filename}/download`, { headers: { Authorization: `Bearer ${getToken()}` } }), }, }, contacts: { list: (params?: string): Promise<Contact[]> => fetchApi(`/api/contacts${params ? `?${params}` : ''}`),
    get: (id: string): Promise<Contact> => fetchApi(`/api/contacts/${id}`), create: (data: Partial<Contact>) => fetchApi('/api/contacts', { method: 'POST', body: JSON.stringify(data) }), update: (id: string, data: Partial<Contact>) => fetchApi(`/api/contacts/${id}`, { method: 'PATCH', body: JSON.stringify(data) }), delete: (id: string) => fetchApi(`/api/contacts/${id}`, { method: 'DELETE' }),
    merge: (targetId: string, sourceIds: string[]) => fetchApi('/api/contacts/merge', { method: 'POST', body: JSON.stringify({ targetId, sourceIds }) }),
    import: (format: 'vcf' | 'csv' | 'xlsx', data: string) => fetchApi('/api/contacts/import', { method: 'POST', body: JSON.stringify({ format, data }) }),
}, deals: { list: (params?: string): Promise<Deal[]> => fetchApi(`/api/deals${params ? `?${params}` : ''}`), create: (data: Partial<Deal>) => fetchApi('/api/deals', { method: 'POST', body: JSON.stringify(data) }), update: (id: string, data: Partial<Deal>) => fetchApi(`/api/deals/${id}`, { method: 'PATCH', body: JSON.stringify(data) }), delete: (id: string) => fetchApi(`/api/deals/${id}`, { method: 'DELETE' }), }, projects: { list: (params?: string): Promise<Project[]> => fetchApi(`/api/projects${params ? `?${params}` : ''}`), get: (id: string): Promise<Project> => fetchApi(`/api/projects/${id}`), create: (data: Partial<Project>) => fetchApi('/api/projects', { method: 'POST', body: JSON.stringify(data) }), update: (id: string, data: Partial<Project>) => fetchApi(`/api/projects/${id}`, { method: 'PATCH', body: JSON.stringify(data) }), delete: (id: string) => fetchApi(`/api/projects/${id}`, { method: 'DELETE' }), }, dashboard: { stats: (): Promise<DashboardStats> => fetchApi('/api/dashboard/stats'), activities: (): Promise<Activity[]> => fetchApi('/api/dashboard/activities'), }, users: { list: (): Promise<User[]> => fetchApi('/api/users'), create: (data: { email: string; password: string; name: string; roleId?: string }) => fetchApi('/api/users', { method: 'POST', body: JSON.stringify(data) }), update: (id: string, data: Partial<User>) => fetchApi(`/api/users/${id}`, { method: 'PATCH', body: JSON.stringify(data) }), delete: (id: string) => fetchApi(`/api/users/${id}`, { method: 'DELETE' }),
    online: () => fetchApi('/api/users/online'),
    heartbeat: () => fetchApi('/api/users/heartbeat', { method: 'POST' }),
    uploadAvatar: (image: string) => fetchApi('/api/users/avatar', { method: 'POST', body: JSON.stringify({ image }) }),
    deleteAvatar: () => fetchApi('/api/users/avatar', { method: 'DELETE' }), }, roles: { list: (): Promise<Role[]> => fetchApi('/api/roles'), create: (data: Partial<Role>) => fetchApi('/api/roles', { method: 'POST', body: JSON.stringify(data) }), update: (id: string, data: Partial<Role>) => fetchApi(`/api/roles/${id}`, { method: 'PATCH', body: JSON.stringify(data) }), delete: (id: string) => fetchApi(`/api/roles/${id}`, { method: 'DELETE' }), }, statuses: { list: (entityType?: string): Promise<Status[]> => fetchApi(`/api/statuses${entityType ? `?entityType=${entityType}` : ''}`), create: (data: Partial<Status>) => fetchApi('/api/statuses', { method: 'POST', body: JSON.stringify(data) }), update: (id: string, data: Partial<Status>) => fetchApi(`/api/statuses/${id}`, { method: 'PATCH', body: JSON.stringify(data) }), delete: (id: string) => fetchApi(`/api/statuses/${id}`, { method: 'DELETE' }), }, profile: { get: (): Promise<User> => fetchApi('/api/profile'), update: (data: Partial<User>) => fetchApi('/api/profile', { method: 'PATCH', body: JSON.stringify(data) }), changePassword: (currentPassword: string, newPassword: string) => fetchApi('/api/profile/change-password', { method: 'POST', body: JSON.stringify({ currentPassword, newPassword }) }), }, comments: { list: (taskId: string): Promise<Comment[]> => fetchApi(`/api/tasks/${taskId}/comments`), create: (taskId: string, content: string, attachmentIds?: string[], isInternal?: boolean) => fetchApi(`/api/tasks/${taskId}/comments`, { method: 'POST', body: JSON.stringify({ content, attachmentIds, isInternal }) }), delete: (taskId: string, commentId: string) => fetchApi(`/api/tasks/${taskId}/comments/${commentId}`, { method: 'DELETE' }), }, push: { vapidKey: () => fetchApi('/api/push/vapid-public-key'), subscribe: (data: any) => fetchApi('/api/push/subscribe', { method: 'POST', body: JSON.stringify(data) }), unsubscribe: (data: any) => fetchApi('/api/push/unsubscribe', { method: 'POST', body: JSON.stringify(data) }), }, emailSettings: { get: (): Promise<EmailSettings | null> => fetchApi('/api/email-settings'), save: (data: Partial<EmailSettings> & { imapPass?: string }) => fetchApi('/api/email-settings', { method: 'POST', body: JSON.stringify(data) }), delete: () => fetchApi('/api/email-settings', { method: 'DELETE' }), }, chat: { list: (afterId?: string): Promise<ChatMessage[]> => fetchApi(`/api/chat${afterId ? `?afterId=${afterId}` : ''}`), send: (content: string, replyToId?: string, recipientIds?: string[], attachmentIds?: string[]) => fetchApi('/api/chat', { method: 'POST', body: JSON.stringify({ content, replyToId, recipientIds, attachmentIds }) }), markAsRead: (messageId: string) => fetchApi(`/api/chat/${messageId}/read`, { method: 'POST' }), delete: (id: string) => fetchApi(`/api/chat/${id}`, { method: 'DELETE' }), react: (messageId: string, emoji: string) => fetchApi(`/api/chat/${messageId}/react`, { method: 'POST', body: JSON.stringify({ emoji }) }), }, uploads: { list: (entityType: string, entityId: string): Promise<FileAttachment[]> => fetchApi(`/api/uploads?entityType=${entityType}&entityId=${entityId}`), upload: (file: File, entityType: string, entityId: string) => { const form = new FormData(); form.append('file', file); form.append('entityType', entityType); form.append('entityId', entityId); return fetch(`${API_URL}/api/uploads`, { method: 'POST', headers: { ...(getToken() ? { Authorization: `Bearer ${getToken()}` } : {}) }, body: form, }).then(r => { if (!r.ok) throw new Error('Upload failed'); return r.json(); }); }, delete: (id: string) => fetchApi(`/api/uploads/${id}`, { method: 'DELETE' }), },
  telephony: {
    getSettings: (): Promise<TelephonySettings | null> => fetchApi('/api/telephony/settings'),
    saveSettings: (data: Partial<TelephonySettings>) => fetchApi('/api/telephony/settings', { method: 'POST', body: JSON.stringify(data) }),
    getCalls: (params?: string): Promise<{ calls: Call[]; total: number }> => fetchApi(`/api/telephony/calls${params ? `?${params}` : ''}`),
    updateCall: (id: string, data: Partial<Call>) => fetchApi(`/api/telephony/calls/${id}`, { method: 'PATCH', body: JSON.stringify(data) }),
    callback: (phone: string, employeeId?: number) => fetchApi('/api/telephony/callback', { method: 'POST', body: JSON.stringify({ phone, employeeId }) }),
    getEmployees: (): Promise<NovofonEmployee[]> => fetchApi('/api/telephony/employees'),
    downloadRecord: (callId: string) => `${API_URL}/api/telephony/records/${callId}/download`,
    getSms: (params?: string): Promise<{ items: SmsMessage[]; total: number }> => fetchApi(`/api/telephony/sms${params ? `?${params}` : ''}`),
  },
  notifications: {
    list: (limit?: number): Promise<{ items: any[]; unreadCount: number }> => fetchApi(`/api/notifications?limit=${limit || 5}`),
    markRead: (id: string) => fetchApi(`/api/notifications/${id}/read`, { method: 'PATCH' }),
    markAllRead: () => fetchApi('/api/notifications/read-all', { method: 'POST' }),
    deleteAll: () => fetchApi('/api/notifications', { method: 'DELETE' }),
  },
  max: {
    getSettings: () => fetchApi('/api/max/settings'),
    saveSettings: (data: any) => fetchApi('/api/max/settings', { method: 'POST', body: JSON.stringify(data) }),
    sendMessage: (chatId: string, text: string) => fetchApi('/api/max/send', { method: 'POST', body: JSON.stringify({ chatId, text }) }),
    getMyChat: () => fetchApi('/api/max/my-chat'),
    linkChat: (chatId: string) => fetchApi('/api/max/link-chat', { method: 'POST', body: JSON.stringify({ chatId }) }),
  },
  beget: {
    account: () => fetchApi('/api/beget/account'),
    domains: () => fetchApi('/api/beget/domains'),
  },
  news: {
    list: (query?: string) => fetchApi(`/api/news${query ? '?' + query : ''}`),
    get: (id: string) => fetchApi(`/api/news/${id}`),
    create: (data: any) => fetchApi('/api/news', { method: 'POST', body: JSON.stringify(data) }),
    update: (id: string, data: any) => fetchApi(`/api/news/${id}`, { method: 'PATCH', body: JSON.stringify(data) }),
    delete: (id: string) => fetchApi(`/api/news/${id}`, { method: 'DELETE' }),
    drafts: () => fetchApi('/api/news/drafts'),
    categories: () => fetchApi('/api/news/categories/list'),
    createCategory: (data: any) => fetchApi('/api/news/categories', { method: 'POST', body: JSON.stringify(data) }),
    updateCategory: (id: string, data: any) => fetchApi(`/api/news/categories/${id}`, { method: 'PATCH', body: JSON.stringify(data) }),
    deleteCategory: (id: string) => fetchApi(`/api/news/categories/${id}`, { method: 'DELETE' }),
    createSubcategory: (data: any) => fetchApi('/api/news/subcategories', { method: 'POST', body: JSON.stringify(data) }),
    updateSubcategory: (id: string, data: any) => fetchApi(`/api/news/subcategories/${id}`, { method: 'PATCH', body: JSON.stringify(data) }),
    deleteSubcategory: (id: string) => fetchApi(`/api/news/subcategories/${id}`, { method: 'DELETE' }),
    tags: () => fetchApi('/api/news/tags/list'),
    createTag: (data: any) => fetchApi('/api/news/tags', { method: 'POST', body: JSON.stringify(data) }),
    updateTag: (id: string, data: any) => fetchApi(`/api/news/tags/${id}`, { method: 'PATCH', body: JSON.stringify(data) }),
    deleteTag: (id: string) => fetchApi(`/api/news/tags/${id}`, { method: 'DELETE' }),
    history: (id: string) => fetchApi(`/api/news/${id}/history`),
    restoreHistory: (id: string, historyId: string) => fetchApi(`/api/news/${id}/history/${historyId}/restore`, { method: 'POST' }),
  },
  tochka: {
    accounts: () => fetchApi('/api/tochka/accounts'),
    customer: () => fetchApi('/api/tochka/customer'),
    status: () => fetchApi('/api/tochka/status'),
    authUrl: () => fetchApi('/api/tochka/auth-url'),
  },
  vkGroupSettings: { get: () => fetchApi('/api/vk-group-settings'), save: (data: any) => fetchApi('/api/vk-group-settings', { method: 'POST', body: JSON.stringify(data) }), delete: () => fetchApi('/api/vk-group-settings', { method: 'DELETE' }), }, camera: {
    getSettings: () => fetchApi('/api/camera/settings'),
    getCamera: (id: string) => fetchApi(`/api/camera/settings/${id}`),
    createCamera: (data: any) => fetchApi('/api/camera/settings', { method: 'POST', body: JSON.stringify(data) }),
    saveCamera: (id: string, data: any) => fetchApi(`/api/camera/settings/${id}`, { method: 'PUT', body: JSON.stringify(data) }),
    deleteCamera: (id: string) => fetchApi(`/api/camera/settings/${id}`, { method: 'DELETE' }),
  },
  taskFinances: {
    get: (taskId: string): Promise<TaskFinances> => fetchApi(`/api/tasks/${taskId}/finances`),
    update: (taskId: string, data: { budget?: number; price?: number }) => fetchApi(`/api/tasks/${taskId}/finances`, { method: 'PATCH', body: JSON.stringify(data) }),
    createTransaction: (taskId: string, data: Partial<TaskTransaction>) => fetchApi(`/api/tasks/${taskId}/transactions`, { method: 'POST', body: JSON.stringify(data) }),
    updateTransaction: (taskId: string, txId: string, data: Partial<TaskTransaction>) => fetchApi(`/api/tasks/${taskId}/transactions/${txId}`, { method: 'PATCH', body: JSON.stringify(data) }),
    deleteTransaction: (taskId: string, txId: string) => fetchApi(`/api/tasks/${taskId}/transactions/${txId}`, { method: 'DELETE' }),
  },
  contactTypes: {
    list: (): Promise<any[]> => fetchApi('/api/contact-types'),
    create: (data: any) => fetchApi('/api/contact-types', { method: 'POST', body: JSON.stringify(data) }),
    update: (id: string, data: any) => fetchApi(`/api/contact-types/${id}`, { method: 'PATCH', body: JSON.stringify(data) }),
    delete: (id: string) => fetchApi(`/api/contact-types/${id}`, { method: 'DELETE' }),
  },
  get: (path: string): Promise<any> => fetchApi(path),

};