-- AlterTable
ALTER TABLE roles ADD COLUMN IF NOT EXISTS notify_on_new_task BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE roles ADD COLUMN IF NOT EXISTS notify_on_new_deal BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE roles ADD COLUMN IF NOT EXISTS notify_on_new_comment BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE roles ADD COLUMN IF NOT EXISTS notify_on_new_chat BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE roles ADD COLUMN IF NOT EXISTS notify_on_new_call BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE roles ADD COLUMN IF NOT EXISTS notify_on_new_news BOOLEAN NOT NULL DEFAULT false;
