import { Router } from 'express';
import { authMiddleware, AuthRequest } from '../middleware/auth.js';
import { prisma } from '../lib/prisma.js';
import { notificationEmitter } from '../lib/notifications.js';
const router = Router();
router.get('/', authMiddleware, async (req: AuthRequest, res) => { try { const { limit = '20', offset = '0', unreadOnly = 'false' } = req.query;
const where: any = { userId: req.user!.id };
if (unreadOnly === 'true') where.readAt = null;
const [items, total, unreadCount] = await Promise.all([ prisma.notification.findMany({ where, orderBy: { createdAt: 'desc' }, take: parseInt(limit as string, 10), skip: parseInt(offset as string, 10) }), prisma.notification.count({ where: { userId: req.user!.id } }), prisma.notification.count({ where: { userId: req.user!.id, readAt: null } }), ]);
res.json({ items, total, unreadCount });
} catch (err: any) { console.error('[Notifications GET Error]', err);
res.status(500).json({ error: err.message });
} });
router.patch('/:id/read', authMiddleware, async (req: AuthRequest, res) => { try { const notif = await prisma.notification.updateMany({ where: { id: req.params.id, userId: req.user!.id }, data: { readAt: new Date() }, });
res.json({ success: true, count: notif.count });
} catch (err: any) { console.error('[Notification Read Error]', err);
res.status(500).json({ error: err.message });
} });
router.post('/read-all', authMiddleware, async (req: AuthRequest, res) => { try { const result = await prisma.notification.updateMany({ where: { userId: req.user!.id, readAt: null }, data: { readAt: new Date() }, });
res.json({ success: true, count: result.count });
} catch (err: any) { console.error('[Notification ReadAll Error]', err);
res.status(500).json({ error: err.message });
} });
router.delete('/:id', authMiddleware, async (req: AuthRequest, res) => { try { await prisma.notification.deleteMany({ where: { id: req.params.id, userId: req.user!.id }, });
res.json({ success: true });
} catch (err: any) { console.error('[Notification Delete Error]', err);
res.status(500).json({ error: err.message });
} });
router.delete('/', authMiddleware, async (req: AuthRequest, res) => { try { const result = await prisma.notification.deleteMany({ where: { userId: req.user!.id }, });
res.json({ success: true, count: result.count });
} catch (err: any) { console.error('[Notification DeleteAll Error]', err);
res.status(500).json({ error: err.message });
} });
router.get('/stream', authMiddleware, (req: AuthRequest, res) => { res.setHeader('Content-Type', 'text/event-stream');
res.setHeader('Cache-Control', 'no-cache');
res.setHeader('Connection', 'keep-alive');
res.flushHeaders();
req.setTimeout(0);
res.setTimeout(0);
const userId = req.user!.id;
const send = (data: any) => { try { res.write('data: ' + JSON.stringify(data) + '\n\n');
} catch (e) { /* client disconnected */ } };
send({ type: 'connected', userId });
const onNotification = (event: { userId: string; notification: any }) => { if (event.userId === userId) { send({ type: 'notification', notification: event.notification });
} };
notificationEmitter.on('notification', onNotification);
const interval = setInterval(() => { try { res.write(':ping\n\n');
} catch (e) { clearInterval(interval);
} }, 30000);
req.on('close', () => { clearInterval(interval);
notificationEmitter.off('notification', onNotification);
res.end();
});
req.on('error', () => { clearInterval(interval);
notificationEmitter.off('notification', onNotification);
res.end();
});
});
export default router ;